---
- name: Install and configure Nginx on localhost
  hosts: localhost
  become: yes
  tasks:
  - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create a custom HTML page
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>Hello, Ansible!</title>
          </head>
          <body>
            <h1>Hello from Ansible Playbook</h1>
            <p>This page is served by Nginx.</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Verify Nginx is running
      shell: systemctl status nginx
      register: nginx_status

    - name: Show Nginx status
      debug:
        var: nginx_status.stdout
