---
- name: Create a file on remote host
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure the directory structure exists
      file:
        path: /home/pnl0r86
        state: directory
        mode: '0755'

    - name: Create an empty file
      file:
        path: /home/pnl0r86/arun.txt
        state: touch
        mode: '0644'


    - name: Verify the file exists
      shell: ls -l /home/pnl0r86/arun.txt
      register: ls_output
      ignore_errors: yes

    - name: Show ls output
      debug:
        var: ls_output.stdout

































# - name: Local Ansible Playbook
#   hosts: localhost
#   become: yes
#   tasks:
#     - name: Ensure Nginx is installed
#       apt:
#         name: nginx
#         state: present
#         update_cache: yes

#     - name: Ensure Nginx is started
#       service:
#         name: nginx
#         state: started
#         enabled: yes

#     - name: Create a file in /tmp directory
#       copy:
#         content: "This is a test file created by Ansible."
#         dest: /tmp/testfile.txt

