---
- name: Create and serve a simple HTML page
  hosts: localhost
  tasks:
    - name: Ensure the directory structure exists
      file:
        path: /tmp/webserver
        state: directory
        mode: '0755'

    - name: Create an HTML file
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
            <title>Hello, Ansible!</title>
          </head>
          <body>
            <h1>Hello from Ansible Playbook</h1>
            <p>This page is served by a basic HTTP server.</p>
          </body>
          </html>
        dest: /tmp/webserver/index.html
        mode: '0644'

    - name: Install Python3 and HTTP server
      become: yes
      apt:
        name: python3
        state: present
        update_cache: yes

    - name: Start a basic HTTP server
      shell: |
        python3 -m http.server 8000 --directory /tmp/webserver &
      args:
        executable: /bin/bash

    - name: Verify the HTML file exists
      shell: ls -l /tmp/webserver/index.html
      register: ls_output
      ignore_errors: yes

    - name: Show ls output
      debug:
        var: ls_output.stdout
