name:  ansible-ci-cd

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
      
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      

      
