name:  ansible-ci-cd
on:
  push:
    branches:
      - arun
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
      
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i localhost, -c local ansible/loop_ansible.yml

      - name: list out the files
        run: |
          cd /tmp
          ls -la

      - name: viewing the github variables
        run: |
          echo "user name is $USER"
          echo "password is $PASSWORD"

      