name:  ansible-ci-cd

on:
  push:
    branches:
      - arun
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
      
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i localhost, -c local ansible/nginx.yml

      - name: Install ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin

      - name: Start ngrok and expose Nginx server
        run: |
          nohup ngrok http 80 > /tmp/ngrok.log 2>&1 &
          sleep 10
          curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url > /tmp/ngrok_url.txt

      - name: Output ngrok URL
        run: cat /tmp/ngrok_url.txt




      
      
          
      

      

      
        

      

      

        

    



      
        
      

      

      
