name:  ansible-ci-cd

on:
  push:
    branches:
      - arun
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
      
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i localhost, -c local ansible/playbook.yml

      - name: Verify HTTP server
        run: |
          sleep 5 # Give the server a moment to start
          curl http://localhost:8000


          

      
      
          
      

      

      
        

      

      

        

    



      
        
      

      

      
