name: firstworkflow
on: push
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hi"
      - name: give the command date
        run: |
          date
      - name: using positional parameters
        run: |
          set Our god is greater
          echo $1 $2 $3
          
