---
name: Creating file as per user input
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment'
        required: true
        type: choice
        options:
          - test
          - acceptance


jobs:
  test:
    if: ${{ github.event.inputs.environment == 'test' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Create file1.txt
        run: echo "This is file1 for test environment" > ironman.txt

      - name: executing the date command
        run: date
      
      - name: listout the file
        run: ls -la
   
  acceptance:
    if: ${{ github.event.inputs.environment == 'acceptance' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Create file20.txt
        run: echo "This is file2 for acceptance environment" > batman.txt  

      - name: listout the file
        run: ls -la
...