name: firstworkflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hi"
      - name: give the command date
        run: |
          date
          
