name: print hello soldieres
on: 
  workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: hello soldiers
        runs: |
          sh bin/hello.sh