name: executing the shell command in ubuntu-latest

on:
  push:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: execute the shell command
        run: |
          echo "Successfully connect the runner"
          ls -lart
          date
          whoami
          mkdir arun
          echo "Thanks for using github action"
  
  Build:
    runs-on: ubuntu-latest
    steps:
  
      - name: Testing the secrets
        env:
          HOPE: ${{ secrets.HOPE }}
        run: |
          echo "$HOPE"



  

