name: Creating file as per user input

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment'
        required: true
        type: choice
        options:
          - test
          - acceptance


jobs:
  test:
    if: ${{ github.event.inputs.environment == 'test' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Create file1.txt
        run: echo "I am iron man" > ironman.txt
  
      - name: listout the file
        run: ls -la
      
      
  acceptance:
    if: ${{ github.event.inputs.environment == 'acceptance' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Create file20.txt
        run: echo "Men are brave" > batman.txt


      - name: listout the file
        run: ls -la









