name: executing the shell command in ubuntu-latest

on:
  push: 
    branches: 
      - arun
  workflow_dispatch:

jobs:
  acc:
    runs-on: ubuntu-latest
    steps:
      - name: execute the shell command
        run: |
          whoami