name: executing the shell command in ubuntu-latest

on:
  push:
    branches:
      - arun
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: execute the shell command
        run: |
          echo "Successfully connect the runner"
          ls -lart
          date
          whoami
  
  # Build:
  #   runs-on: ubuntu-latest
  #   steps:
  
  #     - name: Testing the secrets
  #       env:
  #         HOPE: 'arun'
  #       run: |
  #         echo "${{ secrets.HOPE }}"
  #         echo "${{ env.HOPE }}"



  

