name: print hello world

on:
  
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: pring the hello world
        run: |
          pwd
          echo "hello world"
  
  # Build:
  #   runs-on: ubuntu-latest
  #   steps:
  
  #     - name: Testing the secrets
  #       env:
  #         HOPE: 'arun'
  #       run: |
  #         echo "${{ secrets.HOPE }}"
  #         echo "${{ env.HOPE }}"



  

