name:  ssh connect
on:
  push:
    branches:
      - arun
  workflow_dispatch:
    
    

jobs:

  test:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name:  ssh into vm using username and password & print date
        uses: appleboy/ssh-action@master
        with:
          host: weeus02alfolo01
          username: pnl0r86j
          password: Watch@123
          script: |
            date
            

 
      
    
            
            