name: Syntax Check

on: [pull_request]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 

    - name: Install dependencies
      run: |
        pip install flake8 
        flake8 ansible/nginx.yml
        
        
    # - name: Run syntax check
    #   run: |
    #     flake8 . || exit 1  
