name: Syntax Check

on: [pull_request]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install yamllint
      run: |
        pip install yamllint

    - name: Run yamllint
      run: |
        yamllint ansible/vars/main.yml .github/workflows/main.yml


