name: Syntax Check

on: push

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install yamllint and jsonlint
      run: |
        pip install yamllint
        npm install -g jsonlint
        pip install pyyaml

    - name: Run yamllint
      run: |
        yamllint test.yml

    # - name: Run Python script to validate YAML files
    #   run: python validate.py

    - name: Ensuring the file is checkout to the runner
      run: |
        path='/home/runner/work/git_nagesh/git_nagesh/vars/'
        echo "${path}"
        cd ${path}/test; chmod 755 main.yml; ls -lrt
        cd ${path}/acc; chmod 755 main.yml; ls -lrt
        cd ${path}/prd; chmod 755 main.yml; ls -lrt
        cd ${path}; chmod 755 yaml_precheck.sh; ls -lrt
        cd ${path}

        ./yaml_precheck.sh ${path}/test/main.yml ${path}/acc/main.yml ${path}/prd/main.yml

        #./yaml_precheck.sh

        # chmod 755 /home/runner/work/git_nagesh/git_nagesh/vars/yaml_precheck.sh
        # chmod 755 /home/runner/work/git_nagesh/git_nagesh/vars/test/main.yml
        # ls -lrt


        # /home/runner/work/git_nagesh/git_nagesh/vars/yaml_precheck.sh




        


    
        


