name: Syntax Check
on:
  pull_request:
    branches:
      - main

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install yamllint and jsonlint
      run: |
        pip install yamllint
        npm install -g jsonlint

    - name: Verify installations
      run: |
        yamllint --version
        jsonlint --version

    - name: List system-wide installed packages using yum
      run: yum list installed

    - name: Run yamllint
      run: |
        yamllint vars/acc vars/prd vars/test


