name: Syntax Check

on: push

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Install yamllint and jsonlint
    #   run: |
    #     pip install yamllint
    #     npm install -g jsonlint
    #     pip install pyyaml

    # - name: Run yamllint
    #   run: |
    #     yamllint vars/acc vars/prd vars/test

    # - name: Run Python script to validate YAML files
    #   run: python validate.py
    - name: Ensuring the file is checkout to the runner
      run: |
        ls -lrt
        path='/home/runner/work/git_nagesh/git_nagesh/vars/'
        echo "${path}"
        
        # chmod 755 /home/runner/work/git_nagesh/git_nagesh/vars/yaml_precheck.sh
        # chmod 755 /home/runner/work/git_nagesh/git_nagesh/vars/test/main.yml
        # ls -lrt


        # /home/runner/work/git_nagesh/git_nagesh/vars/yaml_precheck.sh




        


    
        


